-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. FAMILIES TABLE
create table families (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  invite_code text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. PROFILES TABLE (Syncs with auth.users)
-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  family_id uuid references families(id),
  status_message text,

  constraint username_length check (char_length(username) >= 3)
);

-- 3. MESSAGES TABLE
create table messages (
  id uuid default uuid_generate_v4() primary key,
  family_id uuid references families(id) not null,
  user_id uuid references profiles(id) not null,
  text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. TODOS TABLE
create table todos (
  id bigint generated by default as identity primary key,
  family_id uuid references families(id),
  user_id uuid references profiles(id) not null,
  text text not null,
  is_completed boolean default false,
  type text check (type in ('shared', 'personal')),
  assignee_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. PHOTOS TABLE
create table photos (
  id bigint generated by default as identity primary key,
  family_id uuid references families(id) not null,
  user_id uuid references profiles(id) not null,
  url text not null,
  title text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. EVENTS TABLE (Calendar)
create table events (
  id bigint generated by default as identity primary key,
  family_id uuid references families(id) not null,
  user_id uuid references profiles(id) not null,
  title text not null,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles enable row level security;
alter table families enable row level security;
alter table messages enable row level security;
alter table todos enable row level security;
alter table photos enable row level security;
alter table events enable row level security;

-- POLICIES

-- Profiles
create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Families (Allow users to see their own family)
create policy "Families are viewable by members." on families
  for select using (true); -- Simplified for initial setup

create policy "Authenticated users can create families." on families
  for insert with check (auth.role() = 'authenticated');

-- Messages
create policy "Users can view messages from their family." on messages
  for select using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.family_id = messages.family_id
    )
  );

create policy "Users can insert messages to their family." on messages
  for insert with check (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.family_id = messages.family_id
    )
  );

-- Todos (Shared)
create policy "Users can view shared todos from their family." on todos
  for select using (
    (type = 'shared' and exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.family_id = todos.family_id
    ))
    or
    (type = 'personal' and user_id = auth.uid())
  );

create policy "Users can insert todos." on todos
  for insert with check (auth.role() = 'authenticated');

create policy "Users can update todos." on todos
  for update using (auth.role() = 'authenticated');
  
create policy "Users can delete todos." on todos
  for delete using (auth.role() = 'authenticated');

-- Photos & Events (Simplified policies for speed)
create policy "Enable all access for authenticated users" on photos for all using (auth.role() = 'authenticated');
create policy "Enable all access for authenticated users" on events for all using (auth.role() = 'authenticated');

-- Realtime
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table messages, todos, photos, events;


-- Function to handle new user signup with atomic family creation/joining
create or replace function public.handle_new_user()
returns trigger as $$
declare
  f_id uuid;
  signup_type text;
  invite_code text;
  family_name text;
begin
  -- Extract metadata
  signup_type := new.raw_user_meta_data->>'signup_type';
  invite_code := upper(new.raw_user_meta_data->>'invite_code');
  family_name := new.raw_user_meta_data->>'family_name';

  -- 1. Handle Family Logic
  if (signup_type = 'CREATE_FAMILY') then
    -- Create new family
    insert into public.families (name, invite_code)
    values (family_name, invite_code)
    returning id into f_id;
  elsif (signup_type = 'JOIN_FAMILY') then
    -- Find existing family
    select id into f_id from public.families 
    where public.families.invite_code = invite_code
    limit 1;
  end if;

  -- 2. Insert Profile (linked to family if f_id found)
  insert into public.profiles (id, full_name, avatar_url, family_id)
  values (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'avatar_url',
    f_id
  );
  
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on signup (Ensure it only runs once)
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
